### ISSUE TITLE
python 3.8 using jill

### ISSUE THREAD

**Issue by thautwarm** [johnnychen94/jill.py#44]
```
(base) ➜  GitHub jill install 1.6
JILL - Julia Installer 4 Linux (MacOS, Windows and FreeBSD) -- Light

jill will:
  1) install Julia 1.6 for linux-x86_64 into /home/redy/packages/julias
  2) make symlinks in /home/redy/.local/bin
You may need to manually add /home/redy/.local/bin to PATH
Continue installation? [Y/n] y
query the latest 1.6 version, it may take seconds...
----- Download Julia -----
query the latest  version, it may take seconds...
downloading Julia release for 1.5.2-linux-x86_64
downloading from https://mirrors.tuna.tsinghua.edu.cn/julia-releases/bin/linux/x64/1.5/julia-1.5.2-linux-x86_64.tar.gz
100% [......................................................................] 105324048 / 105324048
finished downloading julia-1.5.2-linux-x86_64.tar.gz
downloading from https://mirrors.tuna.tsinghua.edu.cn/julia-releases/bin/linux/x64/1.5/julia-1.5.2-linux-x86_64.tar.gz.asc
100% [..................................................................................] 866 / 866
finished downloading julia-1.5.2-linux-x86_64.tar.gz.asc
verifying 1.5.2-linux-x86_64 succeed
----- Install Julia -----
Traceback (most recent call last):
  File "/home/redy/miniconda3/bin/jill", line 8, in <module>
    sys.exit(main())
  File "/home/redy/miniconda3/lib/python3.8/site-packages/jill/__main__.py", line 15, in main
    fire.Fire({
  File "/home/redy/miniconda3/lib/python3.8/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/redy/miniconda3/lib/python3.8/site-packages/fire/core.py", line 463, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/redy/miniconda3/lib/python3.8/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/redy/miniconda3/lib/python3.8/site-packages/jill/install.py", line 387, in install_julia
    installer(package_path, install_dir, symlink_dir, version, upgrade)
  File "/home/redy/miniconda3/lib/python3.8/site-packages/jill/install.py", line 191, in install_julia_linux
    mver = f_minor_version(version)
  File "/home/redy/miniconda3/lib/python3.8/site-packages/jill/utils/filters.py", line 130, in __call__
    if not self.validate(*args, **kwargs):
  File "/home/redy/miniconda3/lib/python3.8/site-packages/jill/utils/filters.py", line 99, in is_version
    return bool(VERSION_REGEX.match(version))
TypeError: expected string or bytes-like object
```

issues:
1. install from tsinghua tuna mirror when I'm not in mainland China..
2. seems some unhandled case for `version`.
3. 1.6 got me 1.5.2

**Comment by thautwarm** [comment]
If I say `jill install 1.5.2` it works.
You perhaps add a check for this? `TypeError` should be `VersionNotFound`.

**Comment by johnnychen94** [comment]
Hmmm. Yeah, currently it falls back to the latest stable version implicitly but definitely that there are some exceptions not handled properly here.

1.6(rc) is not released yet, so currently you can only get it via `jill install latest` for a nightly build.

It chooses the upstream with the shortest response time, it might be troublesome in some cases. But you could add `jill install latest --upstream Official` to explicitly download from the julialang.org aws s3 bucket.
